### PR TITLE
Added A horse of a different Color

### PR DESCRIPTION
**Pull request by JSchugt**
Added a horse of a different color to the main, with image included.

@eatsleeptravel 
@DavidEdwardDarden

### CODE REVIEW

**Review by dudley-codes — APPROVED** [review]
Looks great!

**Comment by Chadwell-Clark** [comment]
Name is a little long, which makes the image smaller possibly. Otherwise looks great.

**Comment by JSchugt** [comment]
@Chadwell-Clark 

I changed the name to just "Horse".

**Review by SidneyCrandall — APPROVED** [review]
yes. definitely need

**Pull request merged**
