### PR TITLE
Cc fix main

### PR DESCRIPTION
**Pull request by Chadwell-Clark**
Fixed the html . Please check and approve changes

### CODE REVIEW

**Review by jrossgage — APPROVED** [review]
This looks good by my inspection. It opened up well in my browser too. One thing, it appears to have some unnecessary code in the CSS under ".friends img". I know that is outside of the scope of your edits, just wanted to put the observation here. Thanks for doing that edit!

**Comment by Chadwell-Clark** [comment]
Hey Joel, what in the css is unnecessary.  Cheers

**Comment by jrossgage** [comment]
Actually Chad, that was a misunderstanding on my part! I just checked it out this morning and I was mistaken. Looks great!

**Comment by Chadwell-Clark** [comment]
I did not even look at the css before I pushed up this branch, so it would not have surprised me.

**Pull request closed without merging**
